title: Sluit een stereozoemer aan
hero_image: images/banner.png
description: Sluit een stereozoemer aan op een Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - 
    title: Sluit een stereozoemer aan
