
title: Câbler un buzzer stéréo
hero_image: images/banner.png
description: Câbler un buzzer stéréo à un Raspberry Pi Pico
version: 4
listed: false
copyedit: false
last_tested: "2022-02-15"
steps:
  - title: Câbler un buzzer stéréo
